spring.application.name=semana8-patrones-rabbitmq
server.port=8080

camel.springboot.main-run-controller=true

rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=admin
rabbitmq.password=admin123

spring.rabbitmq.host=${rabbitmq.host}
spring.rabbitmq.port=${rabbitmq.port}
spring.rabbitmq.username=${rabbitmq.username}
spring.rabbitmq.password=${rabbitmq.password}

app.rabbitmq.billing-exchange=billing.exchange
app.rabbitmq.orders-exchange=orders.exchange
app.rabbitmq.invalid-exchange=invalid.exchange

app.rabbitmq.billing-queue=billing.queue
app.rabbitmq.notification-queue=notification.queue
app.rabbitmq.analytics-queue=analytics.queue
app.rabbitmq.invalid-queue=invalid-message.queue

app.consumers.billing.enabled=true
app.consumers.billing.second-instance-enabled=false
app.consumers.notification.enabled=true
app.consumers.analytics.enabled=true
app.consumers.error-handler.enabled=true

logging.level.org.apache.camel=INFO
logging.level.edu.udla.integracion.semana8=INFO
